### ISSUE TITLE
networkx.exception.NetworkXError: Graph has no nodes or edges

### ISSUE THREAD

**Issue by vbeliveau** [mnoergaard/petprep_hmc#6]
I took petprep_hmc for a test run and got the following error:

```
> python /staff/vbeliveau/petprep_hmc/run.py --bids_dir /staff/vbeliveau/Cimbi36_Anjali/data --output_dir /staff/vbeliveau/Cimbi36_Anjali/petprep --analysis_level participant --participant_label 52590
FSL is installed at: /usr/local/fsl6.0.4
230504-08:18:35,477 nipype.workflow INFO:
         Workflow petprep_hmc_wf settings: ['check', 'execution', 'logging', 'monitoring']
230504-08:18:35,500 nipype.workflow INFO:
         Running in parallel.
Traceback (most recent call last):
  File "/staff/vbeliveau/petprep_hmc/run.py", line 463, in <module>
    main(args)
  File "/staff/vbeliveau/petprep_hmc/run.py", line 166, in main
    wf = workflow.run(plugin='MultiProc', plugin_args={'n_procs' : int(args.n_procs)})
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-petprep_hmc-test/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-petprep_hmc-test/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 133, in run
    self._generate_dependency_list(graph)
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-petprep_hmc-test/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 447, in _generate_dependency_list
    self.depidx = _graph_to_lil_matrix(graph, nodelist=self.procs)
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-petprep_hmc-test/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 33, in _graph_to_lil_matrix
    return ssp.lil_matrix(to_scipy_sparse_array(graph, nodelist=nodelist, format="lil"))
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-petprep_hmc-test/lib/python3.10/site-packages/networkx/convert_matrix.py", line 550, in to_scipy_sparse_array
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges
```

I made a fresh environment for testing:

```
> pip list
Package            Version   Editable project location
------------------ --------- -------------------------------------
astor              0.8.1
attrs              23.1.0
bids               0.0
bids-validator     1.11.0
certifi            2022.12.7
charset-normalizer 3.1.0
ci-info            0.3.0
click              8.1.3
contourpy          1.0.7
cycler             0.11.0
docopt             0.6.2
etelemetry         0.3.0
filelock           3.12.0
fonttools          4.39.3
formulaic          0.5.2
h5py               3.8.0
idna               3.4
imageio            2.28.1
interface-meta     1.3.0
isodate            0.6.1
Jinja2             3.1.2
joblib             1.2.0
kiwisolver         1.4.4
lazy_loader        0.2
looseversion       1.1.2
lxml               4.9.2
MarkupSafe         2.1.2
matplotlib         3.7.1
networkx           3.1
nibabel            5.1.0
nilearn            0.10.1
nipype             1.8.6
nitransforms       22.0.0
niworkflows        1.7.9
num2words          0.5.12
numpy              1.24.2
packaging          23.1
pandas             2.0.0
patsy              0.5.3
petprep-hmc        0.0.4     /indirect/staff/vbeliveau/petprep_hmc
Pillow             9.5.0
pip                22.0.4
prov               2.0.0
pybids             0.15.6
pydot              1.4.2
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2023.3
PyWavelets         1.4.1
PyYAML             6.0
rdflib             6.3.2
requests           2.29.0
scikit-image       0.20.0
scikit-learn       1.2.2
scipy              1.10.1
seaborn            0.12.2
setuptools         58.1.0
simplejson         3.19.1
six                1.16.0
SQLAlchemy         1.3.24
statsmodels        0.13.5
svgutils           0.3.4
templateflow       23.0.0
threadpoolctl      3.1.0
tifffile           2023.4.12
tqdm               4.65.0
traits             6.3.2
transforms3d       0.4.1
typing_extensions  4.5.0
tzdata             2023.3
urllib3            1.26.15
wrapt              1.15.0
```
```
> python --version
Python 3.10.4

```

**Comment by vbeliveau** [comment]
Unfortunately the issue persists with the latest push (v0.0.5):
```
> python /staff/vbeliveau/Cimbi36_Anjali/petprep_hmc/run.py --bids_dir /staff/vbeliveau/Cimbi36_Anjali/data --output_dir /staff/vbeliveau/Cimbi36_Anjali/petprep --analysis_level participant --participant_label 52590
FSL is installed at: /usr/local/fsl6.0.4
230504-10:45:32,684 nipype.workflow INFO:
         Workflow petprep_hmc_wf settings: ['check', 'execution', 'logging', 'monitoring']
230504-10:45:32,700 nipype.workflow INFO:
         Running in parallel.
Traceback (most recent call last):
  File "/staff/vbeliveau/Cimbi36_Anjali/petprep_hmc/run.py", line 463, in <module>
    main(args)
  File "/staff/vbeliveau/Cimbi36_Anjali/petprep_hmc/run.py", line 166, in main
    wf = workflow.run(plugin='MultiProc', plugin_args={'n_procs' : int(args.n_procs)})
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-test-petprep/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-test-petprep/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 133, in run
    self._generate_dependency_list(graph)
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-test-petprep/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 447, in _generate_dependency_list
    self.depidx = _graph_to_lil_matrix(graph, nodelist=self.procs)
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-test-petprep/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 33, in _graph_to_lil_matrix
    return ssp.lil_matrix(to_scipy_sparse_array(graph, nodelist=nodelist, format="lil"))
  File "/indirect/staff/vbeliveau/Cimbi36_Anjali/.env-test-petprep/lib/python3.10/site-packages/networkx/convert_matrix.py", line 550, in to_scipy_sparse_array
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges
```
```
> pip list | grep petprep
petprep-hmc        0.0.5     /indirect/staff/vbeliveau/Cimbi36_Anjali/petprep_hmc
```

**Comment by mnoergaard** [comment]
Can you try to create a conda environment like this:

conda create --name petprep_hmc python=3.9
conda activate petprep_hmc
git clone https://github.com/mnoergaard/petprep_hmc.git
cd petprep_hmc
pip install -e .

and then run 
python3 /staff/vbeliveau/Cimbi36_Anjali/petprep_hmc/run.py --bids_dir /staff/vbeliveau/Cimbi36_Anjali/data --output_dir /staff/vbeliveau/Cimbi36_Anjali/petprep --analysis_level participant --participant_label 52590

**Comment by mnoergaard** [comment]
I agree - thanks, Vincent! Will start to draft a PR that does this. You are also more than welcome to give it a go.

**Comment by mnoergaard** [comment]
https://github.com/mnoergaard/petprep_hmc/tree/fix_input_output_without_sess_label
